### ISSUE TITLE
Line 260 in sitemap.py assumes that TEMPLATE_PAGES is always a dict, breaks if it is None.

### ISSUE THREAD

**Issue by zalez** [pelican-plugins/sitemap#15]
Hi,

first of all, thanks for this plugin! I'm currently modernizing my blog and plan to use it :).

The Pelican documentation in https://docs.getpelican.com/en/latest/settings.html#template-pages states that `TEMPLATE_PAGES` can be `None`. In fact, this is the default.

However, [line 260 in sitemap.py](https://github.com/pelican-plugins/sitemap/blob/db6f865ea7a0df8d8427f689b7cba2c5941458c2/pelican/plugins/sitemap/sitemap.py#L260) assumes it is always a dict:

>             for path, template_page_url in self.context["TEMPLATE_PAGES"].items():

This breaks whenever `TEMPLATE_PAGES` is `None`, which is the default setting for new Pelican deployments.

I would suggest wrapping this `for` loop into an `if` statement as a fix.

Meanwhile, one workaround is to set `TEMPLATE_PAGES = {}` in `pelicanconf.py` which avoids the issue.

Thanks,
   Constantin

**Comment by justinmayer** [comment]
This should be fixed in v1.1 of the Sitemap plugin, which was just released. 🌟
