### ISSUE TITLE
Error message sitemap: Require numeric priority. Got: 1

### ISSUE THREAD

**Issue by rogerbinns** [pelican-plugins/sitemap#34]
It complained about getting the number 1 which makes the error message rather confusing.  Changing the value in my config to `1.0` fixed the error.

I suggest either changing the word `numeric` to `floating point`, or to accept ints like `1`.

**Comment by justinmayer** [comment]
Thank you for the suggestion, Roger. I have clarified the error message and docs, respectively, via 29f9efe87943b7dcd6ecc7ba7b1b225d163ee553 and f54346f.
