### ISSUE TITLE
Add sitemap link if available

### ISSUE THREAD

**Issue by corentinmusard** [pelican-plugins/sitemap#6]
It would be nice to add a line in `robots.txt` if the [sitemap plugin](https://github.com/pelican-plugins/sitemap) is configured.

Something like:
```
Sitemap: https://www.blog.com/sitemap.xml
```

**Comment by justinmayer** [comment]
@corentinmusard: I transferred this issue to the Sitemap repository. Is this something you would like to work on implementing? As @MaevaBrunelles said, there are no dedicated maintainers for most plugins, and thus progress depends on folks stepping up to implement the features they care about. What say you?

**Comment by corentinmusard** [comment]
Yes I can implement it, that's not a problem.

**Comment by justinmayer** [comment]
@corentinmusard: I'm checking in regarding this issue you submitted a while ago. Are you still interested in adding this feature to the Sitemap plugin?

**Comment by justinmayer** [comment]
Upon further reflection, perhaps this topic is indeed better suited for the SEO plugin. In any case, let's put this on ice until someone wants to implement it.
